### ISSUE TITLE
PINUS database: database design

### ISSUE THREAD

**Issue by emer7** [pinus-it/panutanq#7]
Lanjutan dari #6 

### Design
Each member will have the following fields:
1. Name
2. Contact no
3. Email
4. Major
5. Expected date of graduation
6. Overseas Experience (Exchange/NOC to which country)
7. Internship/Part-time/etc

Database akan bisa di search with parameters of fields above.

Karena database tidak hanya menyangkut dengan mengontrol aksesnya, tetapi juga dengan informasi yang ingin di share oleh tiap" member PINUS, maka untuk database designnya akan allow each member untuk decide whether to share their each fields or not.

### Example:
**Bolded** berarti field itu tidak dishare

| Name | Contact No | Email | Major | Expected date of graduation | Overseas Experience | Internship |
|---|---|---|---|---|---|---|
| Hiro | **1234** | abc[@]cde.f | CS | 2020 | Japan | Google, Facebook |
| John | 1256 | **af[@]fda.ca** | ISE | 2019 | **USA** | **PnG, Unilever** |

End result:

| Name | Contact No | Email | Major | Expected date of graduation | Overseas Experience | Internship |
|---|---|---|---|---|---|---|
| Hiro |  | abc[@]cde.f | CS | 2020 | Japan | Google, Facebook |
| John | 1256 |  | ISE | 2019 |  |  |

**Comment by rvnfdy** [comment]
@emer7 kalo ada yang tidak ingin dishare, apakah perlu diisi? Karena kalau diisi tapi dihidden jadi pointless. Dan lebih mudah implementasinya, bisa dibuat valuenya nullable untuk menandakan kalo tidak mau di share.

**Comment by emer7** [comment]
@rvnfdy kalo engga ingin dishare, tetap dikasih untuk isi saja untuk keperluan arsip PINUS sendiri saja, tapi juga allow null value saja jadi itu terserah mereka mw input atau tidak.

Saya rasa ada column yang bisa nullable seperti overseas experience dan internship, tapi yang tidak bisa nullable seperti nama, contact no, email, major, dan expected date.

Oh juga jangan lupa 1 field lagi, update timestamp jadi orang bisa tau kapan terakhir kali data itu diupdate.
